In [1]:

# importing pandas as pd
import pandas as pd
  
# Creating the DataFrame
df = pd.DataFrame({"A":[12, 4, 5, None, 1], 
                   "B":[7, 2, 54, 3, None], 
                   "C":[20, 16, 11, 3, 8], 
                   "D":[14, 3, None, 2, 6]}) 
  
# Print the DataFrame
print(df)


      A     B   C     D
0  12.0   7.0  20  14.0
1   4.0   2.0  16   3.0
2   5.0  54.0  11   NaN
3   NaN   3.0   3   2.0
4   1.0   NaN   8   6.0


In [2]:
a=df.values
a

array([[12.,  7., 20., 14.],
       [ 4.,  2., 16.,  3.],
       [ 5., 54., 11., nan],
       [nan,  3.,  3.,  2.],
       [ 1., nan,  8.,  6.]])

In [3]:

print(a.shape)
print('filas=',a.shape[0],' Columnas=',a.shape[1])

(5, 4)
filas= 5  Columnas= 4


In [4]:
a[0, 2]

20.0

In [5]:
nans = pd.isnull(a)
nans

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True, False, False, False],
       [False,  True, False, False]])

In [6]:
df.fillna(0)

A     B   C     D
0  12.0   7.0  20  14.0
1   4.0   2.0  16   3.0
2   5.0  54.0  11   0.0
3   0.0   3.0   3   2.0
4   1.0   0.0   8   6.0

In [7]:
adad = pd.DataFrame({"A":[1,2,4,3,4], 
                   "B":[1,2,4,3,4], 
                   "C":[1,2,4,3,4], 
                   "D":[1,2,4,3,4]}) 
abab = pd.DataFrame({"A":[1,-1,4,3,4], 
                   "B":[1,2,4,3,4], 
                   "C":[1,-1,4,3,4], 
                   "D":[1,2,4,3,4]}) 

In [8]:
mask=(adad-abab) /adad.shape[1] >0.5
mask

A      B      C      D
0  False  False  False  False
1   True  False   True  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False

In [9]:
inv_mask = ~mask
inv_mask


A     B      C     D
0   True  True   True  True
1  False  True  False  True
2   True  True   True  True
3   True  True   True  True
4   True  True   True  True

In [10]:
df2 = df[inv_mask]
df2

A     B     C     D
0  12.0   7.0  20.0  14.0
1   NaN   2.0   NaN   3.0
2   5.0  54.0  11.0   NaN
3   NaN   3.0   3.0   2.0
4   1.0   NaN   8.0   6.0

In [11]:
df[mask]

A   B     C   D
0  NaN NaN   NaN NaN
1  4.0 NaN  16.0 NaN
2  NaN NaN   NaN NaN
3  NaN NaN   NaN NaN
4  NaN NaN   NaN NaN

In [17]:
df.index.values



array([0, 1, 2, 3, 4], dtype=int64)

In [22]:
import numpy as np
np.full([200, 4], -1, dtype=np.int32)

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],


In [27]:
def encode_page_features(df):# -> Dict[str, pd.DataFrame]:
    """
    Applies one-hot encoding to page features and normalises result
    :param df: page features DataFrame (one column per feature)
    :return: dictionary feature_name:encoded_values. Encoded values is [n_pages,n_values] array
    """
    def encode(column) -> pd.DataFrame:
        one_hot = pd.get_dummies(df[column], drop_first=False)
        # noinspection PyUnresolvedReferences
        return (one_hot - one_hot.mean()) / one_hot.std()

    return {str(column): encode(column) for column in df}
salida=encode_page_features(df)
salida

{'A':        1.0       4.0       5.0       12.0
 0 -0.447214 -0.447214 -0.447214  1.788854
 1 -0.447214  1.788854 -0.447214 -0.447214
 2 -0.447214 -0.447214  1.788854 -0.447214
 3 -0.447214 -0.447214 -0.447214 -0.447214
 4  1.788854 -0.447214 -0.447214 -0.447214,
 'B':        2.0       3.0       7.0       54.0
 0 -0.447214 -0.447214  1.788854 -0.447214
 1  1.788854 -0.447214 -0.447214 -0.447214
 2 -0.447214 -0.447214 -0.447214  1.788854
 3 -0.447214  1.788854 -0.447214 -0.447214
 4 -0.447214 -0.447214 -0.447214 -0.447214,
 'C':          3         8         11        16        20
 0 -0.447214 -0.447214 -0.447214 -0.447214  1.788854
 1 -0.447214 -0.447214 -0.447214  1.788854 -0.447214
 2 -0.447214 -0.447214  1.788854 -0.447214 -0.447214
 3  1.788854 -0.447214 -0.447214 -0.447214 -0.447214
 4 -0.447214  1.788854 -0.447214 -0.447214 -0.447214,
 'D':        2.0       3.0       6.0       14.0
 0 -0.447214 -0.447214 -0.447214  1.788854
 1 -0.447214  1.788854 -0.447214 -0.447214
 2 -0.447214 -

In [29]:
salida["A"]

1.0       4.0       5.0       12.0
0 -0.447214 -0.447214 -0.447214  1.788854
1 -0.447214  1.788854 -0.447214 -0.447214
2 -0.447214 -0.447214  1.788854 -0.447214
3 -0.447214 -0.447214 -0.447214 -0.447214
4  1.788854 -0.447214 -0.447214 -0.447214

In [31]:
df

A     B   C     D
0  12.0   7.0  20  14.0
1   4.0   2.0  16   3.0
2   5.0  54.0  11   NaN
3   NaN   3.0   3   2.0
4   1.0   NaN   8   6.0

In [35]:
df.median(axis=1)

0    13.0
1     3.5
2    11.0
3     3.0
4     6.0
dtype: float64